// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/kTowkA/GophKeeper/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Storager is an autogenerated mock type for the Storager type
type Storager struct {
	mock.Mock
}

// PasswordHash provides a mock function with given fields: ctx, r
func (_m *Storager) PasswordHash(ctx context.Context, r model.StoragePasswordHashRequest) (model.StoragePasswordHashResponse, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for PasswordHash")
	}

	var r0 model.StoragePasswordHashResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.StoragePasswordHashRequest) (model.StoragePasswordHashResponse, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.StoragePasswordHashRequest) model.StoragePasswordHashResponse); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Get(0).(model.StoragePasswordHashResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.StoragePasswordHashRequest) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, r
func (_m *Storager) Register(ctx context.Context, r model.StorageRegisterRequest) (model.StorageRegisterResponse, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 model.StorageRegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.StorageRegisterRequest) (model.StorageRegisterResponse, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.StorageRegisterRequest) model.StorageRegisterResponse); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Get(0).(model.StorageRegisterResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.StorageRegisterRequest) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStorager creates a new instance of Storager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storager {
	mock := &Storager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
