// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/kTowkA/GophKeeper/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// UserStorager is an autogenerated mock type for the UserStorager type
type UserStorager struct {
	mock.Mock
}

// PasswordHash provides a mock function with given fields: _a0, _a1
func (_m *UserStorager) PasswordHash(_a0 context.Context, _a1 model.StoragePasswordHashRequest) (model.StoragePasswordHashResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PasswordHash")
	}

	var r0 model.StoragePasswordHashResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.StoragePasswordHashRequest) (model.StoragePasswordHashResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.StoragePasswordHashRequest) model.StoragePasswordHashResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(model.StoragePasswordHashResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.StoragePasswordHashRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: _a0, _a1
func (_m *UserStorager) Register(_a0 context.Context, _a1 model.StorageRegisterRequest) (model.StorageRegisterResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 model.StorageRegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.StorageRegisterRequest) (model.StorageRegisterResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.StorageRegisterRequest) model.StorageRegisterResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(model.StorageRegisterResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.StorageRegisterRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserStorager creates a new instance of UserStorager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserStorager(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserStorager {
	mock := &UserStorager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
